//! Parity tests: the Rust engine must reproduce the JS reference exactly.
//!
//! Fixtures are generated by `scripts/gen-parity-fixture.mjs` from the verbatim
//! engine (`core/reference/engine.reference.js`) run over the prototype's inline
//! trilingual DATA. Regenerate with `node scripts/gen-parity-fixture.mjs`.

use mercato_core::decoy::distractors_for;
use mercato_core::distance::BASE;
use mercato_core::matching::Route;
use mercato_core::model::Player;
use mercato_core::rng::Mulberry32;
use mercato_core::Matcher;

use serde::Deserialize;

const PLAYERS_JSON: &str = include_str!("fixtures/players.json");
const CASES_JSON: &str = include_str!("fixtures/cases.json");
const DECOY_JSON: &str = include_str!("fixtures/decoy_cases.json");

#[derive(Deserialize)]
struct Case {
    guess: String,
    player_id: String,
    route: Route,
    ok: bool,
    dist: Option<usize>,
    ambiguous: bool,
}

#[derive(Deserialize)]
struct DecoyCase {
    player_id: String,
    seed: u32,
    expected: Vec<String>,
}

fn players() -> Vec<Player> {
    serde_json::from_str(PLAYERS_JSON).expect("players.json")
}

#[test]
fn matching_parity() {
    let players = players();
    let matcher = Matcher::new(&players);
    let cases: Vec<Case> = serde_json::from_str(CASES_JSON).expect("cases.json");

    let mut failures = 0usize;
    let mut first: Vec<String> = Vec::new();
    for c in &cases {
        let r = matcher
            .match_by_id(&c.guess, &c.player_id, BASE)
            .expect("known player id");
        let ok =
            r.ok == c.ok && r.route == c.route && r.dist == c.dist && r.ambiguous == c.ambiguous;
        if !ok {
            failures += 1;
            if first.len() < 10 {
                first.push(format!(
                    "guess={:?} pid={} => rust(ok={},route={:?},dist={:?},amb={}) vs js(ok={},route={:?},dist={:?},amb={})",
                    c.guess, c.player_id, r.ok, r.route, r.dist, r.ambiguous, c.ok, c.route, c.dist, c.ambiguous
                ));
            }
        }
    }
    assert_eq!(
        failures,
        0,
        "{} / {} matching mismatches. First few:\n{}",
        failures,
        cases.len(),
        first.join("\n")
    );
}

#[test]
fn decoy_parity() {
    let players = players();
    let index: std::collections::HashMap<&str, usize> = players
        .iter()
        .enumerate()
        .map(|(i, p)| (p.id.as_str(), i))
        .collect();
    let cases: Vec<DecoyCase> = serde_json::from_str(DECOY_JSON).expect("decoy_cases.json");

    let mut failures = 0usize;
    let mut first: Vec<String> = Vec::new();
    for c in &cases {
        let pid = index[c.player_id.as_str()];
        let mut rng = Mulberry32::new(c.seed);
        let got: Vec<String> = distractors_for(&players, pid, &mut rng)
            .into_iter()
            .map(|i| players[i].id.clone())
            .collect();
        if got != c.expected {
            failures += 1;
            if first.len() < 10 {
                first.push(format!(
                    "pid={} seed={} => rust={:?} vs js={:?}",
                    c.player_id, c.seed, got, c.expected
                ));
            }
        }
    }
    assert_eq!(
        failures,
        0,
        "{} / {} decoy mismatches. First few:\n{}",
        failures,
        cases.len(),
        first.join("\n")
    );
}
